version: '3.9'
services:
  db:
    image: postgres:15.2
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=refiner_dev
volumes:
  postgres:
