export const programmingLanguageList = [
  { label: 'ABAP', code: 'abap' },
  { label: 'ActionScript', code: 'actionscript' },
  { label: 'Ada', code: 'ada' },
  { label: 'Apex', code: 'apex' },
  { label: 'Assembly', code: 'assembly' },
  { label: 'Batchfile', code: 'batchfile' },
  { label: 'Blockly', code: 'blockly' },
  { label: 'C#', code: 'csharp' },
  { label: 'C++', code: 'cpp' },
  { label: 'Clojure', code: 'clojure' },
  { label: 'Cobol', code: 'cobol' },
  { label: 'CoffeeScript', code: 'coffee' },
  { label: 'CSS', code: 'css' },
  { label: 'D', code: 'd' },
  { label: 'Dart', code: 'dart' },
  { label: 'Dockerfile', code: 'dockerfile' },
  { label: 'DOS', code: 'dos' },
  { label: 'Eiffel', code: 'eiffel' },
  { label: 'Elixir', code: 'elixir' },
  { label: 'Elm', code: 'elm' },
  { label: 'Emacs Lisp', code: 'emacs' },
  { label: 'Erlang', code: 'erlang' },
  { label: 'F#', code: 'fsharp' },
  { label: 'Fortran', code: 'fortran' },
  { label: 'Gherkin', code: 'gherkin' },
  { label: 'Go', code: 'go' },
  { label: 'GraphQL', code: 'graphql' },
  { label: 'Groovy', code: 'groovy' },
  { label: 'Haskell', code: 'haskell' },
  { label: 'HTML', code: 'html' },
  { label: 'IDL', code: 'idl' },
  { label: 'Inform 7', code: 'inform7' },
  { label: 'Java', code: 'java' },
  { label: 'JavaScript', code: 'javascript' },
  { label: 'JSON', code: 'json' },
  { label: 'Julia', code: 'julia' },
  { label: 'Jupyter Notebook', code: 'jupyter' },
  { label: 'Kotlin', code: 'kotlin' },
  { label: 'Less', code: 'less' },
  { label: 'Lisp', code: 'lisp' },
  { label: 'Lua', code: 'lua' },
  { label: 'Makefile', code: 'makefile' },
  { label: 'Markdown', code: 'markdown' },
  { label: 'MATLAB', code: 'matlab' },
  { label: 'Modelica', code: 'modelica' },
  { label: 'Nim', code: 'nim' },
  { label: 'NSIS', code: 'nsis' },
  { label: 'Objective-C', code: 'objc' },
  { label: 'OCaml', code: 'ocaml' },
  { label: 'OpenEdge ABL', code: 'openedge' },
  { label: 'Pascal', code: 'pascal' },
  { label: 'Perl', code: 'perl' },
  { label: 'PHP', code: 'php' },
  { label: 'PostScript', code: 'postscript' },
  { label: 'PowerShell', code: 'powershell' },
  { label: 'Prolog', code: 'prolog' },
  { label: 'Python', code: 'python' },
  { label: 'Q#', code: 'qsharp' },
  { label: 'R', code: 'r' },
  { label: 'Red', code: 'red' },
  { label: 'ReScript', code: 'rescript' },
  { label: 'Ruby', code: 'ruby' },
  { label: 'Rust', code: 'rust' },
  { label: 'SAS', code: 'sas' },
  { label: 'Sass', code: 'sass' },
  { label: 'Scala', code: 'scala' },
  { label: 'Scheme', code: 'scheme' },
  { label: 'Scratch Blocks', code: 'scratchblocks' },
  { label: 'Scratch', code: 'scratch' },
  { label: 'Shell', code: 'shell' },
  { label: 'Smalltalk', code: 'smalltalk' },
  { label: 'Snap!', code: 'snap' },
  { label: 'SPARQL', code: 'sparql' },
  { label: 'SQL', code: 'sql' },
  { label: 'Swift', code: 'swift' },
  { label: 'TeX', code: 'tex' },
  { label: 'Turing', code: 'turing' },
  { label: 'Tynker Blocks', code: 'tynkerblocks' },
  { label: 'TypeScript', code: 'typescript' },
  { label: 'VBScript', code: 'vbscript' },
  { label: 'Verilog', code: 'verilog' },
  { label: 'VHDL', code: 'vhdl' },
  { label: 'Vim script', code: 'vimscript' },
  { label: 'Visual Basic', code: 'vb' },
  { label: 'WebAssembly', code: 'wasm' },
  { label: 'XML', code: 'xml' },
  { label: 'YAML', code: 'yaml' },
]

export const FREE_USAGE_LIMIT = 3
